- hosts: docker-slave
  tasks:
   - name: Hi. I ensure connecting to the Docker machine
     ping:
   - name: Create slave Docker bibinwilson 
     docker_container:
      docker_host: "tcp://{{ansible_ssh_host}}:4243"
      image: sriniwilson/jenkins-slave
      state: started
      tty: True
      name: dockerslave
      command: "git clone https://github.com/jenkinsassignment/dockeransibleproj.git"