- hosts: all
  tasks:
   - name: Hi. I ensure connecting to the machine
     ping:
   - name: Run Docker bibinwilson slave
     docker:
      image: bibinwilson/jenkins-slave
      name: DockerContainer
      state: running