- tasks:
   - name: Hi. I ensure connecting to the machine
     host: docker-slave
     ping:
   - name: Create slave : Docker bibinwilson
     docker-container:
      docker_host: tcp://192.168.2.204:4243
      image: bibinwilson/jenkins-slave
      state: present
      name: docker-slave
   - name: Run the build inside the Docker slave
     shell: java -jar jenkins-cli.jar -s tcp://192.168.2.204:4243 build builds/$BUILD_NUMBER --username jenkins --password jenkins
      