- hosts: docker-slave
  tasks:
   - name: Hi. I ensure connecting to the Docker machine
     ping:
   - name: Create slave Docker bibinwilson 
     docker_container:
      docker_host: "tcp://192.168.2.204:4243"
      image: sriniwilson/jenkins-slave
      state: started
      name: dockerslave
      command: "git clone https://github.com/jenkinsassignment/dockeransibleproj.git"