- hosts: all
  tasks:
   - name: Hi. I ensure connecting to the Docker machine
     hosts: docker-slave
     ping:
   - name: Create slave Docker bibinwilson
     hosts: jenkins-master
     docker:
      docker_host: tcp://192.168.2.204:4243
      image: bibinwilson/jenkins-slave
      state: present
      name: dockerslave
   - name: Run the build inside the Docker slave
     hosts: jenkins-master
     tasks:
     shell: "java -jar jenkins-cli.jar -s tcp://192.168.2.204:4243 build builds/$BUILD_NUMBER --username jenkins --password jenkins"