- name: Hi. I ensure connecting to the machine
  hosts: docker-slave
  ping:
- name: Create slave Docker bibinwilson
  docker:
   docker_host: tcp://192.168.2.204:4243
   image: bibinwilson/jenkins-slave
   state: present
   name: dockerslave
- name: Run the build inside the Docker slave
  hosts: jenkins-master
  shell: "java -jar jenkins-cli.jar -s tcp://192.168.2.204:4243 build builds/$BUILD_NUMBER --username jenkins --password jenkins"