- hosts: all
  become: true
  tasks:
   - name: Hi. I ensure connecting to the machine
     ping:
   - name: Run Docker bibinwilson slave
     shell: sudo docker run bibinwilson/jenkins-slave --name slave_ansible