- hosts: jenkins-master
  tasks:
   - name: Hi. I ensure connecting to the Docker machine
     ping:
   - name: Create slave Docker bibinwilson 
     docker_container:
      docker_host: "tcp://{{slave}}:4243"
      recreate: yes
      image: sriniwilson/jenkins-slave
      state: started
      name: dockerslave
      command: "git clone https://github.com/jenkinsassignment/dockeransibleproj.git"